### ISSUE TITLE
Unexpected behaviour for io:get_line/1

### ISSUE THREAD

**Issue by tamarit** [erlang/erlide_eclipse#215]
Hi,

I'm trying to read a string from the Console, but when I call to `io:get_line/1` this function always returns the atom ok without waiting for an input. 

```erlang
> io:get_line("").
ok
```

Is there an alternative way to read a string in erlide? 
Or, do you plan to change this behaviour in the future?

Thanks in advance.

**Comment by vladdu** [comment]
Hi! The console in erlide is a bit tricky to implement fully. At the moment, I chose to leave out input in order to be able to support code completion and the like for the console input. Implementing the rest is planned, but there are many other things in the pipeline. I will bump up the priority now, but I can't promise anything.

The workaround is to start your erlang node from the command line using the same name that erlide would give it. Then when launching it from erlide, it detects that it is already running and just connects to it. You can use the terminal to interact with your program and changes in the editor will still be reloaded automatically.

**Comment by vladdu** [comment]
Hi! The console in erlide is a bit tricky to implement fully. At the moment, I chose to leave out input in order to be able to support code completion and the like for the console input. Implementing the rest is planned, but there are many other things in the pipeline. I will bump up the priority now, but I can't promise anything.

The workaround is to start your erlang node from the command line using the same name that erlide would give it. Then when launching it from erlide, it detects that it is already running and just connects to it. You can use the terminal to interact with your program and changes in the editor will still be reloaded automatically.

**Comment by tamarit** [comment]
Hi Vlad,

first of all thanks for your quick and interesting answer. We have been trying to do the communication using the trick you mentioned, but we are failing to get results. We have followed your instructions. We run the node, and try to call `io:get_line/1` from the eclipse's console. Unfortunately, the erlang node give the following error

```
=INFO REPORT==== 25-Mar-2015::17:56:02 ===
erlide_shell:handle_io_request: Unexpected IORequest:{get_line,unicode,[]}
```

and erlide's console simply returns atom `ok` and waits for another expression to evaluate. 
Are we still doing something wrong?
Thanks.

**Comment by vladdu** [comment]
You have to call io:get_line from the terminal shell, as it is a "normal", fully functional shell.

**Comment by tamarit** [comment]
Yes, in this way I can read from the standard input in the terminal shell. However, eclipse's console does not seem to realize of what I'm doing in the terminal shell, and also the other way around.

**Comment by vladdu** [comment]
No, of course not. You have to do all interaction (starting your program, etc) from the terminal.

**Comment by tamarit** [comment]
I understand now. So the idea is just replace one shell for the other. The benefits in doing so is to have the code reloaded when it's changed in Eclipse. It's clear. 

Thanks for you help Vlad.
