### ISSUE TITLE
Not know how to debug Erlang in Eclipse.

### ISSUE THREAD

**Issue by liangdefeng** [erlang/erlide_eclipse#316]
I am new to Erlang, and I am to learn Erlang because of project need. I have a problem in debugging Erlang in ErlIDE in Eclipse.

I followed the instructions given in the following page.
http://erlide.org/articles/eclipse/280_Running-and-debugging-Erlang-code.html
I run the debugger, the program won't stop on the break points I set in the program. Not sure where the problem is?

Here is my environment info.
1. Eclise
Eclipse for PHP Developers
Version: Oxygen.1a Release (4.7.1a)
Build id: 20171005-1200
OS: Windows 7, v.6.1, x86_64 / win32
2. Erlang language tools IDE 0.52.2.201707181448
3. Erlang 9.2

**Comment by vladdu** [comment]
The docs are a bit short. Please try this (assuming your code is in only one project) :
- in your code, set a breakpoint
- right-click the project in the explorer view, and choose "debug as -> erlang application"
- this will bring up an erlang shell, where you can run your application
- hopefully the breakpoint is reached, and the debug perspective is shown

Probably easiest is to try it first with a simple "hello world" example, like in the tutorials, except choose "debug" instead of "run".

Please let me know how it goes, and if it doesn't work, what happens.

**Comment by vladdu** [comment]
Please reopen if you still have problems.

**Comment by MPC-BlackBox** [comment]
Hi, I am trying to setup a erlang ide using eclipse. I have followed all the setup information with success.

I can run the following test code:
start() ->
   Bin1 = <<10,20>>,
   X = binary_to_list(Bin1),
   io:fwrite("~w",[X]).

Trying to manually setup debug configuration does not work but debug as erlang application fills in all the boxes and it does work.

Only issue is break points do not work. They are ignored.

Debug config settings are attached below.

erlide - Erlang language tools	0.56.0.201909301105

![config1](https://user-images.githubusercontent.com/59446384/72273252-f0344700-3621-11ea-83f8-69ca1e4cdee6.JPG)
![Config2](https://user-images.githubusercontent.com/59446384/72273264-f4f8fb00-3621-11ea-9786-7ef58fef6d4b.JPG)
![config3](https://user-images.githubusercontent.com/59446384/72273268-f75b5500-3621-11ea-9433-a2d9f3ff5015.JPG)

Any ideas greatly appreciated.

Thanks MPC.
